dist: trusty
sudo: false
language: php

env:
  global:
    - TEST="./vendor/bin/phpunit --verbose"
    - COMPOSER_UP="composer update --no-interaction --prefer-dist --no-progress --profile --no-suggest"

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

before_install:
  - stty cols 120
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - chmod a+x ./build/travis/configure_php.sh
  - ./build/travis/configure_php.sh
  - composer validate

install:
  - composer global require hirak/prestissimo
  - $COMPOSER_UP

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot
  include:
    - stage: Test
      php: 7.3
      env: REMOVE_XDEBUG=true
    - stage: Test
      php: 7.4snapshot
      env: REMOVE_XDEBUG=true
    - stage: Test
      php: nightly
      env: REMOVE_XDEBUG=true

    - stage: Coverage
      php: 7.3
      env: REMOVE_XDEBUG=false
      script:
        - bash -xc "$TEST -c ./phpunit.xml.dist --coverage-clover=coverage.xml"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always
